# Embedding

## Why Embedding?
As we know, machines can't handle text, it can only handle numbers. But how to convert a word to numbers?

The most naive approach would be to take a list of all the words in your text and attribute a number to all of them. It will work but you can imagine that some problems will appear:
* How do you handle unknown words? 
* If your text contains `doctor`, `nurse`, and `candy`. `doctor` and `nurse` have a strong correlation but `candy` doesn't. How can we make the machine understand that? With our naive technique, `doctor` could have the number `5` associated to it and nurse the number `98767`.

Of course, a lot of people already spent some time with those problems. the solution that came out of it is "Embedding". 

## What is embeddings?

An embedding is a **VECTOR** which represents a word or a document.

A vector will be attributed to each token. Each vector will contain multiple dimensions (usually tens or hundreds of dimensions).

```
[...] associate with each word in the vocabulary a distributed word feature vector [...] The feature vector represents different aspects of the word: each word is associated with a point in a vector space. The number of features [...] is much smaller than the size of the vocabulary.
```
- [A Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf), 2003.

Long story short, embeddings convert words into vectors in a way that allows the machine to understand the similarity betweens them.

Each embedding library has it's own way of classifying words, it will regroup words into big categories. Each word will get a score for each category.

To take a simple example the word `mother` could be classified like that:

|        | female | family | human | animal|
|--------|--------|---------|-------|-------|
| mother | 0.9    | 0.9.    | 0.7   | 0.1   |

**Explanations:** Mother has a strong correlation with female, family and human but it has a low correlation with animal.

**Disclaimer:** Those numbers and categories are totally arbitrary and are only here to show an example.

Here is another example with more complete datas:

![embedding](https://miro.medium.com/max/2598/1*sAJdxEsDjsPMioHyzlN3_A.png)

## Should I do it by hand?

You could, but if some people already did the job for you and spent a lot of time to optimize it, why not use it?

## What to use?

There are a lot of libraries out there for embeddings. Which one is the best? Once again, *it depends*. The results will change depending on the text you are using, the information you want to extract, the model you use,...

Choosing the "best" embedding model will be part of the hyper-optimization that you can do at the end of a project.

If you want understand embeddings more in depth, [follow this link](http://jalammar.github.io/illustrated-word2vec/)

Here are some of the best libraries of the moment:

* [Flair](https://github.com/flairNLP/flair) (University of Berlin)
* [fasttext](https://fasttext.cc/) (Facebook)
* [GloVe](https://github.com/stanfordnlp/GloVe) (Stanford)

And the oldest way doing it (but still good):
* [Word2Vec](https://www.tensorflow.org/tutorials/text/word2vec)

## Stack embeddings

The previous embeddings are good, but if you want something even better, you can "stack" these embeddings to create a bigger vector. It gives better results but will also require more computation power.

[Here is a super clear and understandable guide](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md) to get it done. (by the Flair's team)

## Practice time!

Enough reading, let's practice a bit. Can you use SpaCy to embed this sentence?
Read the [spacy embedding documentation](https://spacy.io/usage/vectors-similarity)

In [10]:
sentence = "I love learning"
import spacy

nlp = spacy.load("en_core_web_md")
tokens = nlp(sentence)
for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)
# Embed `sentence` with SpaCy

I True 6.4231944 False
love True 6.04035 False
learning True 6.542082 False


What is the shape of each word's vector?

In [9]:
for token in tokens:
    print(token.vector.shape)

(300,)
(300,)
(300,)


Try with Flair now.

In [13]:
from flair.data import Sentence
from flair.embeddings import FlairEmbeddings

# init embedding
flair_embedding_forward = FlairEmbeddings('news-forward')

sentence = "I love learning"
sentence = Sentence(sentence)

# embed words in sentence
flair_embedding_forward.embed(sentence)

# now check out the embedded tokens.
for token in sentence:
    print(token)
    print(token.embedding)

# Embed `sentence` with Flair

2021-02-02 09:51:36,492 https://flair.informatik.hu-berlin.de/resources/embeddings/flair/news-forward-0.4.1.pt not found in cache, downloading to /tmp/tmpozhmnfij


100%|██████████| 73034624/73034624 [00:23<00:00, 3102343.76B/s]

2021-02-02 09:52:00,194 copying /tmp/tmpozhmnfij to cache at /home/becode/.flair/embeddings/news-forward-0.4.1.pt
2021-02-02 09:52:00,277 removing temp file /tmp/tmpozhmnfij


Token: 1 I
tensor([ 0.0040,  0.0002,  0.0748,  ..., -0.0040,  0.0220,  0.0052])
Token: 2 love
tensor([-2.8628e-04, -8.3362e-05,  2.4466e-03,  ..., -3.9199e-03,
        -1.2964e-02,  4.7443e-03])
Token: 3 learning
tensor([-0.0001,  0.0002,  0.0244,  ..., -0.0041, -0.0057,  0.0073])


What is the shape of each word's vector?

In [16]:
for token in sentence:
    print(token.embedding.shape)

torch.Size([2048])
torch.Size([2048])
torch.Size([2048])


Do the same with Fasttext

In [ ]:
sentence = "I love learning"


# Embed `sentence` with Fasttext

What is the shape of each word's vector?

Do the same with GloVe

In [17]:
from flair.embeddings import WordEmbeddings
from flair.data import Sentence

# init embedding
glove_embedding = WordEmbeddings('glove')

In [20]:
sentence = "I love learning"

# create sentence.
sentence = Sentence(sentence)

# embed a sentence using glove.
glove_embedding.embed(sentence)

# now check out the embedded tokens.
for token in sentence:
    print(token)
    
# Embed `sentence` with glove

Token: 1 I
Token: 2 love
Token: 3 learning


What is the shape of each word's vector?

In [21]:
for token in sentence:
    print(token.embedding.shape)

torch.Size([100])
torch.Size([100])
torch.Size([100])


Your text is now embedded, your model will be able to understand it, yeah!


## More resources
* [Why do we use word embeddings in NLP?](https://towardsdatascience.com/why-do-we-use-embeddings-in-nlp-2f20e1b632d2)
* [More details on what word embeddings are exactly?](https://www.analyticsvidhya.com/blog/2017/06/word-embeddings-count-word2veec/)